name: Maven Build and Deploy to Tomcat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build WAR inside webapp directory
        run: |
          cd webapp
          mvn clean package

      - name: Undeploy previous version from Tomcat (if exists)
        env:
          TOMCAT_URL: http://44.203.181.56:8081
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}
        run: |
          curl -v -u "$TOMCAT_USER:$TOMCAT_PASS" "$TOMCAT_URL/manager/text/undeploy?path=/webapp" || true

      - name: Deploy WAR to Tomcat
        env:
          TOMCAT_URL: http://44.203.181.56:8081
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}
        run: |
          WAR_FILE=$(find webapp/target -name "*.war" | head -n 1)
          if [ -z "$WAR_FILE" ]; then
            echo "Error: WAR file not found in webapp/target directory"
            exit 1
          fi
          echo "Deploying WAR file: $WAR_FILE to $TOMCAT_URL"
          curl -v -u "$TOMCAT_USER:$TOMCAT_PASS" \
            --upload-file "$WAR_FILE" \
            "$TOMCAT_URL/manager/text/deploy?path=/webapp&update=true"
